import { Buffer } from "buffer";
import { Octokit } from "@octokit/rest";
import { getIncidentById } from "./incidentService";

type CreatePrInput = {
  incidentId: string;
  repoUrl: string;
  token: string;
};

function parseRepo(repoUrl: string) {
  const cleaned = repoUrl
    .replace("https://github.com/", "")
    .replace("http://github.com/", "")
    .replace(".git", "")
    .trim();

  const [owner, repo] = cleaned.split("/");

  if (!owner || !repo) {
    throw new Error("Repository must be in the format owner/repo");
  }

  return { owner, repo };
}

function toBase64(content: string) {
  return Buffer.from(content, "utf-8").toString("base64");
}

function isAlreadyExistsError(error: unknown) {
  if (typeof error !== "object" || error === null) return false;

  const maybeStatus = error as { status?: number; message?: string };

  return (
    maybeStatus.status === 422 ||
    maybeStatus.message?.toLowerCase().includes("reference already exists") === true
  );
}

export async function createGithubPr({
  incidentId,
  repoUrl,
  token
}: CreatePrInput) {
  const incident = getIncidentById(incidentId);

  if (!incident || !incident.dna || !incident.artifacts) {
    throw new Error("Incident, Failure DNA, or artifacts not found");
  }

  const { owner, repo } = parseRepo(repoUrl);
  const octokit = new Octokit({ auth: token });

  const repoInfo = await octokit.repos.get({
    owner,
    repo
  });

  const defaultBranch = repoInfo.data.default_branch;

  const baseRef = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`
  });

  const baseSha = baseRef.data.object.sha;
  const branchName = `incidentbrain/fix-${incidentId}`;

  try {
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha
    });
  } catch (error) {
    if (!isAlreadyExistsError(error)) {
      throw error;
    }
  }

  const files = [
    {
      path: `incidentbrain/${incidentId}/alert-rule.yml`,
      content: incident.artifacts.alert_yaml
    },
    {
      path: `incidentbrain/${incidentId}/runbook-patch.md`,
      content: incident.artifacts.runbook_md
    },
    {
      path: `incidentbrain/${incidentId}/terraform-guard.tf`,
      content: incident.artifacts.terraform_tf
    }
  ];

  for (const file of files) {
    let existingSha: string | undefined;

    try {
      const existingFile = await octokit.repos.getContent({
        owner,
        repo,
        path: file.path,
        ref: branchName
      });

      if (!Array.isArray(existingFile.data) && "sha" in existingFile.data) {
        existingSha = existingFile.data.sha;
      }
    } catch {
      existingSha = undefined;
    }

    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file.path,
      message: `IncidentBrain: add prevention artifact ${file.path}`,
      content: toBase64(file.content),
      branch: branchName,
      sha: existingSha
    });
  }

  const pr = await octokit.pulls.create({
    owner,
    repo,
    title: `IncidentBrain: Prevention fix for ${incident.dna.title}`,
    head: branchName,
    base: defaultBranch,
    body: `## IncidentBrain Prevention Fix

Incident ID: ${incidentId}

### Failure DNA Summary
${incident.dna.summary}

### Trigger
${incident.dna.trigger}

### Detection Gap
${incident.dna.detection_gap}

### Blast Radius
${incident.dna.blast_radius}

### Generated Artifacts
- Prometheus alert rule
- Runbook patch
- Terraform guard

This PR was generated by IncidentBrain Advanced.`
  });

  return {
    pr_url: pr.data.html_url,
    branch: branchName
  };
}
